### ISSUE TITLE
How to remove units?

### ISSUE THREAD

**Issue by furieuxjk** [yuxincs/aioapcaccess#18]
Hey!

Is it possible to remove units from the output data? For example, remove Volts, Percent, Minutes etc and leave only values.

Original APCUPd utility apcaccess does it with -u flag.

**Comment by yuxincs** [comment]
You can use the helper function `split_unit` to split values and units. See https://github.com/yuxincs/aioapcaccess#usage

Feel free to reopen if that doesn't solve the problem 😃

**Comment by furieuxjk** [comment]
Yes, I thought I should use split_unit function but I don't know where in the code I should put it.
Could you please give an example?

**Comment by yuxincs** [comment]
`split_unit` is really just a helper function which takes a string and returns a tuple of strings `(value, unit)`. The `unit` will be `None` if it cannot find a supported unit to split.

For example, `split_unit("2.0 Volts") == ("2.0", "Volts")` and `split_unit("2.0") == ("2.0", None)`.

So, after you have requested the status (via `request_status`), which returns an ordered dict, you can use `split_unit` on all the values to further split the units from the raw output for each item.
